<?php

namespace Base\DependencyInjection;

use Base\Imagine\Filter\Basic\Definition\UltraHighDefinitionFilter;
use Base\Service\Model\IconProvider\Adapter\FontAwesomeAdapter;
use Base\Service\TimeMachine;
use Symfony\Component\Config\Definition\Builder\TreeBuilder;
use Symfony\Component\Uid\Uuid;

use Base\Bundle\AbstractBaseConfiguration;

class BaseConfiguration extends AbstractBaseConfiguration
{
    public function getConfigTreeBuilder(): TreeBuilder
    {
        $treeBuilder = $this->getTreeBuilder();
        $treeBuilder->getRootNode()
        ->children()
            ->booleanNode('autoclear')
                ->info('Automatically clear cache in case of integrity issue')
                ->defaultValue(true)
            ->end()

            ->arrayNode('database')->addDefaultsIfNotSet()
            ->children()

                ->booleanNode('fallback_warning')
                    ->info('Fallback warning disable in case there is no fallback')
                    ->defaultValue(true)
                ->end()

                ->booleanNode('use_custom')
                    ->info('Use custom database settings')
                    ->defaultValue(null)
                ->end()

                ->arrayNode('excluded_fields')
                    ->defaultValue(['id', 'locale', 'translatable'])
                    // ->beforeNormalization()
                    //     ->then(function ($v) { return preg_split('/\s*,\s*/', $v); })
                    //     ->end()
                ->prototype('scalar')
                    ->info('Global list of fields to exclude from form generation. (Default: id, locale, translatable)')->end()
                    ->end()
                ->end()
            ->end()

            ->arrayNode('share')
            ->arrayPrototype()
                ->children()
                    ->scalarNode("id")->end()
                    ->scalarNode("url")->end()
                    ->end()
                ->end()
            ->end()

            ->arrayNode('user')->addDefaultsIfNotSet()

                ->children()
                ->scalarNode('token_default_throttling')
                    ->info('Default throttling time between two tokens received')
                    ->defaultValue(3*60)
                    ->end()
                ->end()

                ->children()
                ->scalarNode('login_with_token')
                    ->info('Allow using a token sent by email')
                    ->defaultValue(false)
                    ->end()
                ->end()

                ->children()
                    ->scalarNode('identifier')
                        ->info('Property used to identity user')
                        ->defaultValue("email")
                        ->end()
                    ->integerNode('active_delay')
                        ->info('Threshold considering user as inactive ("active delay" is expected to be lower than "online delay")')
                        ->defaultValue(60)
                        ->end()
                    ->integerNode('online_delay')
                        ->info('Threshold considering user as offline')
                        ->defaultValue(60*5)
                        ->end()
                    ->arrayNode('notifications')
                        ->children()
                            ->scalarNode('expiry')
                                ->info('Time before erasing data if read')
                                ->defaultValue("+30d")
                                ->end()
                            ->end()
                        ->end()
                    ->arrayNode('register')
                        ->children()
                            ->booleanNode('autoapprove')
                                ->info('Administrator check required')
                                ->defaultValue(false)
                                ->end()
                            ->booleanNode('notify_admins')
                                ->info('Administrator are notify when someone register')
                                ->defaultValue(false)
                                ->end()
                            ->end()
                        ->end()
                ->end()
            ->end()

            ->arrayNode('access_restriction')->addDefaultsIfNotSet()
                ->children()
                    ->scalarNode('redirect_on_deny')
                        ->info('Redirection in case of access restriction')
                        ->defaultValue(null)
                    ->end()

                    ->booleanNode('public_access')
                        ->info('Access to public visitors')
                        ->defaultValue(true)
                    ->end()

                    ->booleanNode('user_access')
                        ->info('Access to users')
                        ->defaultValue(true)
                    ->end()

                    ->booleanNode('admin_access')
                        ->info('Access to administrators')
                        ->defaultValue(true)
                    ->end()

                    ->arrayNode('firewalls')
                        ->addDefaultChildrenIfNoneSet()
                            ->prototype('scalar')
                            ->defaultValue('main')
                        ->end()
                    ->end()

                    ->arrayNode('route_exceptions')
                        ->info('Routes (regular expressions on their names) no access restriction stops, and the referrer never remembers: the sign-in pages, the language switch, the UX endpoints.')
                        ->prototype('scalar')->end()
                        ->defaultValue(['/^(?:locale_|ux_|user_|security_)/'])
                    ->end()

                    ->arrayNode('exceptions')
                        ->arrayPrototype()->addDefaultsIfNotSet()
                            ->children()
                                ->scalarNode('locale')
                                    ->defaultValue(null)
                                ->end()
                                ->scalarNode('env')
                                    ->defaultValue(null)
                                ->end()
                                ->scalarNode('host')
                                    ->info('Regex ')
                                    ->defaultValue(null)
                                ->end()
                                ->scalarNode('path')
                                    ->info('Regex ')
                                    ->defaultValue(null)
                                ->end()
                                ->scalarNode('domain')
                                    ->info('Regex ')
                                    ->defaultValue(null)
                                ->end()
                                ->scalarNode('subdomain')
                                    ->info('Regex ')
                                    ->defaultValue(null)
                                ->end()
                                ->scalarNode('scheme')
                                    ->info('Regex ')
                                    ->defaultValue(null)
                                ->end()
                            ->end()
                        ->end()
                    ->end()
                ->end()
            ->end()

            ->arrayNode('site')->addDefaultsIfNotSet()
                ->children()
                    ->scalarNode('index')
                        ->info('Website home page')
                        ->defaultValue("app_index")
                        ->end()
                    ->arrayNode('maintenance')->addDefaultsIfNotSet()
                        ->children()
                            ->scalarNode('redirect_on_deny')
                                ->info('Maintenance redirection')
                                ->defaultValue("maintenance")
                                ->end()
                            ->arrayNode('exception')
                                ->prototype('scalar')->end()
                                    ->useAttributeAsKey('code')
                                    ->prototype('scalar')->end()
                                    ->defaultValue([])
                                ->end()
                            ->scalarNode('lockpath')
                                ->info('Maintenance lock file location')
                                ->defaultValue("%kernel.project_dir%/public/maintenance.lock")
                            ->end()
                        ->end()
                    ->end()
                ->end()
            ->end()

            ->arrayNode('router')->addDefaultsIfNotSet()
                ->children()
                    ->booleanNode('use_custom')
                        ->info('Use custom router')
                        ->defaultValue(null)
                        ->end()

                    ->booleanNode('ip_access')
                        ->info('Allow accessing by')
                        ->defaultValue(false)
                    ->end()

                    ->booleanNode('use_fallbacks')
                        ->info('Restrict to permitted hosts')
                        ->defaultValue(false)
                    ->end()

                    ->booleanNode('fallback_warning')
                        ->info('Fallback warning disable in case there is no fallback')
                        ->defaultValue(true)
                    ->end()

                    ->arrayNode('host_fallbacks')
                        ->arrayPrototype()->addDefaultsIfNotSet()
                            ->children()
                                ->scalarNode('locale')
                                    ->defaultValue(null)
                                ->end()
                                ->scalarNode('env')
                                    ->defaultValue('%env(APP_ENV)%')
                                ->end()
                                ->booleanNode('reduction')
                                    ->defaultValue(null)
                                ->end()
                                ->variableNode('subdomain')
                                    ->info('Sub-domain')
                                    ->defaultValue([])
                                ->end()
                                ->variableNode('machine')
                                    ->info('Machine name')
                                    ->defaultValue([])
                                ->end()
                                ->variableNode('domain')
                                    ->info('Domain')
                                    ->defaultValue([])
                                ->end()
                                ->variableNode('port')
                                    ->info('Port number')
                                    ->defaultValue([80])
                                ->end()
                                ->scalarNode('base_dir')
                                    ->info('Base directory')
                                    ->defaultValue("/")
                                ->end()
                            ->end()
                        ->end()
                    ->end()
                ->end()
            ->end()

            ->arrayNode('translator')->addDefaultsIfNotSet()
                ->children()
                    ->enumNode('politeness')
                        ->values([null, 'plain', 'polite', 'formal'])
                        ->defaultNull()
                        ->info('How the site addresses people (docs/20-architecture/politeness.md): a text asked without a level of its own is taken in its "._plain", "._polite" or "._formal" variant when the catalogue has one (formal falls back on polite), else as it is. Unset: the texts as they are written.')
                    ->end()
                ->end()
            ->end()

            ->arrayNode('parameter_bag')->addDefaultsIfNotSet()

                ->children()
                    ->booleanNode('use_setting_bag')
                        ->info('Use setting bag from database')
                        ->defaultValue(null)
                    ->end()
                    ->booleanNode('use_hot_bag')
                        ->info('Use hot bag parameter rewriting')
                        ->defaultValue(null)
                    ->end()
                ->end()
            ->end()

            ->arrayNode('notifier')->addDefaultsIfNotSet()

                ->children()

                    ->booleanNode('mailer')
                        ->info('Enable mailer')
                        ->defaultValue(true)
                    ->end()

                    ->booleanNode('technical_loopback')
                        ->info('Do not allow sending email until loopback is removed')
                        ->defaultValue(true)
                    ->end()

                    ->arrayNode('technical_recipient')->addDefaultsIfNotSet()
                    ->children()
                        ->scalarNode('email')
                            ->info('Technical contact email')
                            ->defaultValue(null)
                            ->end()
                        ->scalarNode('phone')
                            ->info('Default phone number')
                            ->defaultValue(null)
                            ->end()
                        ->end()
                    ->end()
                    ->scalarNode('admin_role')
                        ->info('Administrators receiving notifications')
                        ->defaultValue("ROLE_EDITOR")
                    ->end()
                    ->arrayNode('test_recipients')
                        ->addDefaultChildrenIfNoneSet()
                            ->prototype('scalar')
                            ->defaultValue('@localhost$')
                        ->end()
                    ->end()
                    ->arrayNode('options')
                        ->arrayPrototype()
                            ->children()
                                ->scalarNode("channel")->end()
                                ->scalarNode("markAsRead")->end()
                            ->end()
                        ->end()
                    ->end()
                ->end()
            ->end()
            ->arrayNode('spam')->addDefaultsIfNotSet()
                ->children()
                    ->scalarNode('akismet')
                        ->info('AKISMET API Key')
                        ->defaultValue("")
                        ->end()
                ->end()
            ->end()
            ->arrayNode('time_machine')->addDefaultsIfNotSet()
                ->children()
                    ->scalarNode('compression')
                        ->info('Default compression algorithm')
                        ->defaultValue("gzip")
                        ->end()
                    ->scalarNode('time_limit')
                        ->info('Default time limit before deleting')
                        ->defaultValue("+30 days")
                        ->end()
                    ->integerNode('max_cycle')
                        ->info('Default compression algorithm')
                        ->defaultValue(-1)
                        ->end()
                    ->scalarNode('snapshot_dir')
                        ->info('Directory the snapshot is staged in before transfer (defaults to the kernel cache directory)')
                        ->defaultValue(null)
                        ->end()
                    ->arrayNode('excludes')
                        ->info('Paths left out of the application tarball')
                        ->scalarPrototype()->end()
                        ->defaultValue(TimeMachine::DEFAULT_EXCLUDES)
                        ->end()
                ->end()
            ->end()
            ->arrayNode('icon_provider')->addDefaultsIfNotSet()
                ->children()
                    ->scalarNode('default_adapter')
                        ->info('Default icon provider class')
                        ->defaultValue(FontAwesomeAdapter::class)
                        ->end()
                ->end()
            ->end()

            ->arrayNode('uploader')->addDefaultsIfNotSet()
                ->children()
                ->booleanNode('warmup')
                    ->info('Automatic image uploader warmup')
                    ->defaultValue(true)
                    ->end()
                ->scalarNode('storage')
                    ->info('Upload storage location')
                    ->defaultValue(null)
                    ->end()
                ->arrayNode('formats')
                    ->arrayPrototype()
                        ->info("Specific formats")
                        ->children()
                            ->scalarNode("class")->end()
                            ->scalarNode("property")->end()
                            ->scalarNode("width")->end()
                            ->scalarNode("height")->end()
                            ->end()
                        ->end()
                    ->end()
                    ->end()
                ->end()

            ->arrayNode('files')->addDefaultsIfNotSet()
                ->children()
                    ->scalarNode('storage')
                        ->defaultValue(null)
                        ->end()
                    ->end()
                ->end()

            ->arrayNode('images')->addDefaultsIfNotSet()
                ->children()
                    ->scalarNode('max_resolution')
                        ->defaultValue(UltraHighDefinitionFilter::class)
                        ->end()
                    ->booleanNode('autorotate')
                        ->defaultValue(true)
                        ->end()
                    ->booleanNode('debug')
                        ->defaultValue(false)
                        ->end()
                    ->booleanNode('disable_profiler')
                        ->defaultValue(true)
                        ->end()
                    ->scalarNode('max_quality')
                        ->defaultValue(1)
                        ->end()
                    ->scalarNode('timeout')
                        ->defaultValue(60)
                        ->end()
                    ->scalarNode('enable_webp')
                        ->defaultValue(true)
                        ->end()
                    ->arrayNode('no_image')
                        ->defaultValue([
                            ["extension" => "webp", "path" => "%kernel.project_dir%/public/bundles/base/images/image.webp"], 
                            ["extension" => "jpg" , "path" => "%kernel.project_dir%/public/bundles/base/images/image.jpg" ], 
                            ["extension" => "jpeg", "path" => "%kernel.project_dir%/public/bundles/base/images/image.jpg" ], 
                            ["extension" => "png" , "path" => "%kernel.project_dir%/public/bundles/base/images/image.png" ], 
                            ["extension" => "svg" , "path" => "%kernel.project_dir%/public/bundles/base/images/image.svg" ], 
                            ["extension" => "gif" , "path" => "%kernel.project_dir%/public/bundles/base/images/image.gif" ], 
                        ])
                        ->arrayPrototype()
                        ->info("Replacement image")
                        ->children()
                            ->scalarNode("extension")->end()
                            ->scalarNode("path")->end()
                            ->end()
                        ->end()
                    ->end()
                    ->booleanNode('fallback')
                        ->defaultValue(false)
                        ->end()
                    ->scalarNode('warmup')
                        ->defaultValue(true)
                        ->end()
                ->arrayNode('formats')
                    ->arrayPrototype()
                        ->info("Specific formats")
                        ->children()
                            ->scalarNode("class")->end()
                            ->scalarNode("property")->end()
                            ->scalarNode("width")->end()
                            ->scalarNode("height")->end()
                            ->end()
                        ->end()
                    ->end()
                ->end()
            ->end()
            ->arrayNode('paginator')->addDefaultsIfNotSet()
                ->children()
                    ->integerNode('page_range')
                        ->info('Range around the current page')
                        ->defaultValue(1)
                        ->end()
                    ->integerNode('page_size')
                        ->info('Number of element per page')
                        ->defaultValue(10)
                        ->end()
                    ->scalarNode('page_parameter')
                        ->info('Default parameter name in route')
                        ->defaultValue("page")
                        ->end()
                    ->scalarNode('default_template')
                        ->info('Default template used to display pages in sliding control')
                        ->defaultValue("@Base/paginator/sliding.html.twig")
                        ->end()
                ->end()
            ->end()
            ->arrayNode('obfuscator')->addDefaultsIfNotSet()
                ->children()
                    ->integerNode('level')
                        ->info('Compression level')
                        ->defaultValue(-1)
                        ->end()
                    ->scalarNode('uuid')
                        ->info('Use uuid shortening')
                        ->defaultValue(Uuid::NAMESPACE_URL)
                        ->end()
                    ->integerNode('encoding')
                        ->info('Compression encoding')
                        ->defaultValue(null)
                        ->end()
                    ->integerNode('max_length')
                        ->info('Decoding max length')
                        ->defaultValue(0)
                        ->end()
                    ->scalarNode('compression')
                        ->info('Compression algorithm')
                        ->defaultValue("null")
                        ->end()
                    ->scalarNode('cache_dir')
                        ->info('Identifier-map storage directory; must survive cache:clear/deploys or previously-issued short URLs become permanently unresolvable')
                        ->defaultValue("%kernel.cache_dir%")
                        ->end()
                ->end()
            ->end()
            ->arrayNode('twig')->addDefaultsIfNotSet()
                ->children()
                    ->arrayNode('breakpoints')
                        ->arrayPrototype()
                            ->children()
                                ->scalarNode("name")->end()
                                ->scalarNode("media")->end()
                            ->end()
                        ->end()
                    ->end()

                    ->arrayNode('themes')->addDefaultsIfNotSet()
                        ->children()
                            ->arrayNode('audiences')
                                ->useAttributeAsKey('name')
                                ->arrayPrototype()
                                    ->children()
                                        ->integerNode('age')->defaultNull()->end()
                                        ->scalarNode('icon')->defaultNull()->end()
                                    ->end()
                                ->end()
                            ->end()
                            ->arrayNode('widths')
                                ->useAttributeAsKey('name')
                                ->arrayPrototype()
                                    ->children()
                                        ->scalarNode('icon')->defaultNull()->end()
                                        ->scalarNode('class')->defaultNull()->end()
                                    ->end()
                                ->end()
                            ->end()
                            ->scalarNode('default_audience')
                                ->info('Default audience key among valid audiences')
                                ->defaultValue(null)
                                ->end()
                            ->arrayNode('events')
                                ->useAttributeAsKey('name')
                                ->arrayPrototype()
                                    ->children()
                                        ->scalarNode('begin')->defaultNull()->end()
                                        ->scalarNode('end')->defaultNull()->end()
                                        ->integerNode('priority')->defaultValue(0)->end()
                                        ->scalarNode('icon')->defaultNull()->end()
                                    ->end()
                                ->end()
                            ->end()
                            ->arrayNode('modes')
                                ->useAttributeAsKey('name')
                                ->arrayPrototype()
                                    ->children()
                                        ->scalarNode('class')->defaultNull()->end()
                                        ->scalarNode('icon')->defaultNull()->end()
                                        ->scalarNode('prefers')->defaultNull()->end()
                                    ->end()
                                ->end()
                                ->defaultValue([
                                    ['name' => 'auto', 'icon' => 'fa-solid fa-fw fa-circle-half-stroke'],
                                    ['name' => 'dark', 'icon' => 'fa-solid fa-fw fa-moon'],
                                    ['name' => 'light', 'icon' => 'fa-solid fa-fw fa-sun']
                                ])
                            ->end()
                            ->arrayNode('filters')
                                ->useAttributeAsKey('name')
                                ->arrayPrototype()
                                    ->children()
                                        ->scalarNode('icon')->defaultNull()->end()
                                        ->scalarNode('filter')->defaultNull()->end()
                                    ->end()
                                ->end()
                            ->end()
                        ->end()
                    ->end()

                    ->arrayNode('script_attributes')->addDefaultsIfNotSet()
                        ->children()
                            ->scalarNode('defer')
                                ->defaultValue(false)
                                ->end()
                            ->scalarNode('async')
                                ->defaultValue(false)
                                ->end()
                            ->booleanNode('ordered')
                                ->defaultTrue()
                                ->info('Scripts run in the order of the page: a file named -async is loaded defer. The core\'s base-async sets window.jQuery, which the site\'s entries read as an external; false brings back async, with no guarantee that it runs first.')
                                ->end()
                        ->end()
                    ->end()
                    ->arrayNode('link_attributes')->addDefaultsIfNotSet()
                        ->children()
                            ->scalarNode('defer')
                                ->defaultValue(false)
                                ->end()
                            ->scalarNode('async')
                                ->defaultValue(false)
                                ->end()
                        ->end()
                    ->end()

                    ->booleanNode('use_custom')
                        ->info('Use base filesystem loader')
                        ->defaultValue(null)
                        ->end()
                    ->booleanNode('use_form2')
                        ->info('Use custom base form style')
                        ->defaultValue(true)
                        ->end()
                    ->booleanNode('use_ea')
                        ->info('Include EA form style')
                        ->defaultValue(true)
                        ->end()
                    ->booleanNode('use_bootstrap')
                        ->info('Use bootstrap style in forms')
                        ->defaultValue(true)
                        ->end()
                    ->booleanNode('autoappend')
                        ->info('Autoappend required dependencies in html content')
                        ->defaultValue(true)
                        ->end()
                    ->scalarNode('default_path')
                        ->info('Default twig path')
                        ->defaultValue("%kernel.project_dir%/vendor/glitchr/omnibase/templates")
                        ->end()
                    ->arrayNode('form_themes')
                        ->addDefaultChildrenIfNoneSet()
                            ->prototype('scalar')
                            ->defaultValue('./form/form_div_layout.html.twig')
                            ->end()
                    ->end()

                    ->arrayNode('editor')->addDefaultsIfNotSet()
                    ->children()
                        ->scalarNode('storage')
                            ->defaultValue(null)
                            ->end()
                        ->end()
                    ->end()

                    ->arrayNode('paths')
                        ->arrayPrototype()
                            ->children()
                                ->scalarNode("path")->end()
                                ->scalarNode("namespace")->end()
                                ->end()
                            ->end()
                        ->end()
                    ->end()
            ->end()

            ->arrayNode('attributes')->addDefaultsIfNotSet()
                ->children()
                    ->booleanNode('use_custom')
                        ->info('Use custom attribute reader')
                        ->defaultValue(null)
                        ->end()
                    ->arrayNode('paths')
                        ->addDefaultChildrenIfNoneSet()
                            ->prototype('scalar')
                                ->defaultValue('%kernel.project_dir%/src/Attribute')
                        ->end()
                    ->end()
                ->end()
            ->end()

            // Account security decided by the application (the administrator's own switches are settings: Base\Service\SecurityPolicy).
            ->arrayNode('security')->addDefaultsIfNotSet()
                ->children()
                    ->arrayNode('two_factor')->addDefaultsIfNotSet()
                        ->children()
                            ->arrayNode('required_roles')
                                ->info('Roles whose holders must have a second factor (directly or through the role hierarchy), e.g. [ROLE_STAFF]. Empty: the administrator\'s "mandatory for everyone" setting alone decides. A later definition (when@dev, when@test, another file) replaces the list, it does not add to it.')
                                // A list is merged by appending: when@test's [] left the base list as it was, and
                                // when@dev's [ROLE_ADMIN] gave [ROLE_STAFF, ROLE_ADMIN]. The last definition is the list.
                                ->performNoDeepMerging()
                                ->scalarPrototype()->end()
                                ->defaultValue([])
                                ->end()
                            ->booleanNode('postpone')
                                ->info('Whether the enrolment prompt offers a "not now" (kept for the session). False: an account a second factor is required of is sent back to the prompt on every page until it has one.')
                                ->defaultTrue()
                                ->end()
                        ->end()
                    ->end()
                ->end()
            ->end()

            // The `demo` environment (docs/20-architecture/demo.md). Read in every environment, acted on in `demo` only.
            ->arrayNode('demo')->addDefaultsIfNotSet()
                ->children()
                    ->scalarNode('production_database')
                        ->info('The DSN of the production database ("mysql://host:3306/name"; user and password are not compared). The demo environment refuses to start on it - and refuses to start while this is unset.')
                        ->defaultNull()
                        ->end()
                    ->scalarNode('superadmin_password')
                        ->info('The super-administrator\'s password in the demo environment: a secret (DEMO_SUPERADMIN_PASSWORD). Unset or empty: no account whose roles reach ROLE_SUPERADMIN can sign in there.')
                        ->defaultValue('%env(default::DEMO_SUPERADMIN_PASSWORD)%')
                        ->end()
                    ->arrayNode('exclude')
                        ->info('Identifiers of declared demonstration accounts this site leaves out.')
                        ->scalarPrototype()->end()
                        ->defaultValue([])
                        ->end()
                    ->arrayNode('reset')->addDefaultsIfNotSet()
                        ->children()
                            ->arrayNode('purge')
                                ->info('Directories demo:reset empties before it reloads the fixtures: the files visitors sent to a storage of the application\'s own.')
                                ->scalarPrototype()->end()
                                ->defaultValue([])
                                ->end()
                            ->arrayNode('groups')
                                ->info('The fixture groups demo:reset loads (doctrine:fixtures:load --group). Empty: every fixture.')
                                ->scalarPrototype()->end()
                                ->defaultValue([])
                                ->end()
                            ->booleanNode('orphans')
                                ->info('Whether demo:reset deletes the uploaded files no row names any more (uploader:entities --delete-orphans).')
                                ->defaultTrue()
                                ->end()
                        ->end()
                    ->end()
                ->end()
            ->end()

            // The shared bricks (docs/40-commons): opening hours, comments, signed downloads.
            ->arrayNode('opening_hours')->addDefaultsIfNotSet()
                ->children()
                    ->scalarNode('timezone')->defaultValue('Europe/Paris')->info('The timezone the hours are given in.')->end()
                    ->scalarNode('cutoff')->defaultNull()->info('"HH:MM": past it, orderDay() is the next open day. Null: the day itself until it closes.')->end()
                    ->variableNode('week')->defaultValue([])->info('The usual week until one is saved (hoursWeekDay): ISO day (1 = Monday) => [["09:00", "13:00"], ...].')->end()
                ->end()
            ->end()

            // schema.org's LocalBusiness (docs/40-commons/local-business.md): what the back office's settings do not say.
            ->arrayNode('local_business')->addDefaultsIfNotSet()
                ->children()
                    ->scalarNode('type')->defaultValue('LocalBusiness')->info('The schema.org type: LocalBusiness, or one of its kinds (Restaurant, Store, Dentist, ProfessionalService...).')->end()
                    ->scalarNode('name')->defaultNull()->info('Null: the site\'s title (base.settings.title).')->end()
                    ->scalarNode('url')->defaultNull()->info('Null: the site\'s home address.')->end()
                    ->scalarNode('telephone')->defaultNull()->info('Null: the setting base.settings.phone.')->end()
                    ->scalarNode('email')->defaultNull()->end()
                    ->scalarNode('image')->defaultNull()->info('A path under public/ ("assets/ico/android-chrome-512x512.png") or an address.')->end()
                    ->scalarNode('price_range')->defaultNull()->info('"€€", "10-50 €"...')->end()
                    ->arrayNode('address')->addDefaultsIfNotSet()
                        ->children()
                            ->scalarNode('street')->defaultNull()->end()
                            ->scalarNode('postal_code')->defaultNull()->end()
                            ->scalarNode('locality')->defaultNull()->end()
                            ->scalarNode('region')->defaultNull()->end()
                            ->scalarNode('country')->defaultNull()->info('ISO 3166-1 alpha-2: FR.')->end()
                        ->end()
                    ->end()
                    ->arrayNode('geo')->addDefaultsIfNotSet()
                        ->children()
                            ->floatNode('latitude')->defaultNull()->end()
                            ->floatNode('longitude')->defaultNull()->end()
                        ->end()
                    ->end()
                    ->arrayNode('same_as')->scalarPrototype()->end()->defaultValue([])->info('The business elsewhere: its Facebook, Instagram, LinkedIn pages.')->end()
                    ->arrayNode('area_served')->scalarPrototype()->end()->defaultValue([])->end()
                    ->variableNode('extra')->defaultValue([])->info('Any other schema.org property, merged as it is: {parentOrganization: {"@type": Organization, name: PANO}}.')->end()
                ->end()
            ->end()

            // The forms' guard (Base\Service\FormGuard, the option `guard` of a form; docs/20-architecture/guard.md).
            ->arrayNode('guard')->addDefaultsIfNotSet()
                ->children()
                    ->scalarNode('challenge')->defaultNull()->info('The captcha: a gateway of omnishield.gateways. Null: omnishield.challenge.gateway when glitchr/omnishield is installed; false: none.')->end()
                    ->scalarNode('fallback')->defaultNull()->info('The captcha shown to a visitor who refused the third party the captcha reaches (consent): a gateway that reaches nobody, ALTCHA.')->end()
                    ->arrayNode('reputation')->scalarPrototype()->end()->defaultValue([])->info('The lists asked about whoever submits (IP address, e-mail, name): gateways of omnishield.gateways - disposable, stopforumspam.')->end()
                    ->scalarNode('classifier')->defaultNull()->info('The classifier of what is written (SpamChecker): a gateway of omnishield.gateways. Null: Akismet with the key api.spam.akismet (base.spam.akismet) when omnishield/akismet is installed.')->end()
                    ->enumNode('unreachable')->values(['accept', 'reject'])->defaultValue('accept')->info('A list or a classifier that does not answer: the form goes on (accept) or is refused (reject). The captcha\'s is omnishield.challenge.unreachable.')->end()
                    ->integerNode('min_delay')->min(0)->defaultValue(3)->info('Seconds between a guarded form being shown and sent: faster is a robot. 0: not checked.')->end()
                    ->integerNode('sign_in_after')->min(0)->defaultValue(3)->info('Failed sign-ins from an address before the sign-in form asks the captcha too. 0: never.')->end()
                    ->integerNode('captcha_after')->min(0)->defaultValue(3)->info('Refused tries of a guarded form from a visitor (address, else session; 15 minutes) before its captcha is shown and asked. 0: always shown. A form sets its own with the option guard.captcha_after.')->end()
                ->end()
            ->end()

            // Documents signed through glitchr/omnisign (Base\Service\Signatures): only with that family.
            ->arrayNode('signatures')->addDefaultsIfNotSet()
                ->children()
                    ->scalarNode('gateway')->defaultNull()->info('The gateway envelopes go through: one of omnisign.gateways. Null: the only one configured.')->end()
                    ->scalarNode('storage')->defaultNull()->info('The private Flysystem storage the signed documents and their evidence are kept in. Null: the uploads\' (base.uploader.storage).')->end()
                ->end()
            ->end()

            ->arrayNode('comments')->addDefaultsIfNotSet()
                ->children()
                    ->integerNode('min_delay')->min(0)->defaultValue(4)->info('Seconds between a comment form being opened and sent: faster is a robot.')->end()
                    ->integerNode('flood_interval')->min(0)->defaultValue(60)->info('Seconds between two comments from the same address.')->end()
                ->end()
            ->end()

            ->arrayNode('vault')->addDefaultsIfNotSet()
                ->children()
                    ->booleanNode('allow_plaintext')->defaultFalse()->info('#[Vault]: without the environment\'s key pair (bin/console secrets:generate-keys), store a secured field in clear instead of refusing it. Off: the save fails with VaultKeyNotFoundException.')->end()
                ->end()
            ->end()

            ->arrayNode('download_links')->addDefaultsIfNotSet()
                ->children()
                    ->integerNode('ttl')->min(1)->defaultValue(600)->info('Seconds a signed download link stays valid.')->end()
                ->end()
            ->end()

            ->arrayNode('extension')->addDefaultsIfNotSet()
                ->children()
                ->scalarNode('max_revisions')
                    ->info('Max number of revision for a given entity')
                    ->defaultValue(5)
                    ->end()
                ->scalarNode('empty_trash')
                    ->info('Time before hard deletion')
                    ->defaultValue(5)
                    ->end()
                ->scalarNode('logging_default_expiry')
                    ->info('Default logging expiry')
                    ->defaultValue(3*60)
                    ->end()
        ->end();

        return $treeBuilder;
    }
}
